### ISSUE TITLE
项目readme里边需要添加一个FAQ部分，请大家提供下FAQ问题

### ISSUE THREAD

**Issue by beimen** [x140yu/Developing_iOS_8_Apps_With_Swift#121]
如题。

**Comment by bluekurk** [comment]
新手较多的话，链接个 “提问的智慧” 吧

**Comment by Hs-Yeah** [comment]
如何参与翻译、校对？——先进入 issue 领取任务，分配任务后先确认收到，再执行任务，完成任务后创建 PR 来提交任务。
课件会翻译吗？——之前有尝试过，但是因为课件体积较大，不方便传输，所以后来放弃。

**Comment by inrenping** [comment]
怎么在fork之后保持本地文件的持续更新？

**Comment by AustinChou** [comment]
@inrenping 设置本地仓库的上游分支（upstream branch），然后 git pull upstream master
