### ISSUE TITLE
「任务分配」6. Protocols and Delegation, Gestures

### ISSUE THREAD

**Issue by beimen** [x140yu/Developing_iOS_8_Apps_With_Swift#122]
要参加第六课翻译的同学，请到这个issue底下回复，说明自己想要翻译还是校对。
因为x140yu回家过年，没那么多时间上网，所以由我发布。
希望大家翻译的时候能认真，把视频看过一遍再翻译，不要硬对着字幕翻译。
质量是第一的，速度可以慢。

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 200|zobnec|true|true
|201 ~ 400|ShadowPlayer|true|true
|401 ~ 600|yang0013|true|true
|601 ~ 800|AustinChou|true|true
|801 ~ 1000|bluekurk|true|true
|1001 ~ 1200|whatya|true|true
|1201 ~ 1400|yuzixun|true|true
|1401 ~ 1600|AustinChou|true|true
|1601 ~ 1766|michaelpassion|true|true

## 校对人员

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|Hs-Yeah|true
|301 ~ 600|guyigenius|true|true
|601 ~ 900|yang0013|true|true
|901 ~ 1200|AustinChou|true|true
|1201 ~ 1500|iSmartie|true|true
|1501 ~ 1766|x140yu|true|true

**Comment by Hs-Yeah** [comment]
领校对任务

**Comment by zobnec** [comment]
领翻译任务

**Comment by guyigenius** [comment]
领校对任务

**Comment by ShadowPlayer** [comment]
领翻译或校对.

**Comment by yang0013** [comment]
领翻译或校对.

**Comment by li-xinyang** [comment]
领取翻译任务 不想用QQ

**Comment by AustinChou** [comment]
翻译或校对

**Comment by whatya** [comment]
领翻译

**Comment by yuzixun** [comment]
领翻译 too~

**Comment by bluekurk** [comment]
翻译任务

**Comment by AustinChou** [comment]
@zobnec @ShadowPlayer @yang0013 @li-xinyang @whatya @yuzixun 翻译任务已经分配

**Comment by Bintong** [comment]
感觉校对和翻译都可以的，不过不知道如何领任务，是不是还要经过项目持有者确认才能开始做啊

**Comment by yang0013** [comment]
假期归来，确认收到任务，明天提交～

**Comment by whatya** [comment]
第六课还有没有没翻译的？

**Comment by x140yu** [comment]
@ShadowPlayer @yang0013 @li-xinyang 请确认收到翻译任务，否则任务会移交给他人

**Comment by ShadowPlayer** [comment]
确认

**Comment by yang0013** [comment]
确认

**Comment by iSmartie** [comment]
领校对任务

**Comment by TongFangyuan** [comment]
领翻译任务

**Comment by ShadowPlayer** [comment]
我的部分明后天提交.

**Comment by x140yu** [comment]
@Hs-Yeah @guyigenius @yang0013 @AustinChou @iSmartie 请确认校对任务

**Comment by guyigenius** [comment]
校对任务已经收到

**Comment by iSmartie** [comment]
校对任务收到

**Comment by Hs-Yeah** [comment]
校对任务收到

**Comment by yang0013** [comment]
校队任务收到
