### ISSUE TITLE
中文字幕乱码反馈用的issue

### ISSUE THREAD

**Issue by beimen** [x140yu/Developing_iOS_8_Apps_With_Swift#131]
如果您遇到外挂字幕时的乱码，请将这个字幕是第几课告诉我们。

如果可以，你请用文本编辑器打开字幕文件（.srt文件），然后以UTF-8的编码方式保存，再用播放器外挂字幕，就可以使用。

**Comment by junweiyang** [comment]
唉  百度视频里面看第二课没有字幕 请修正下 写了！

**Comment by huangshisong** [comment]
我这里乱码  怎么弄的啊 亲  我用了暴风影音和VLC

**Comment by 03128crz** [comment]
唉，使用文本编辑打开以UTF-8保存还是方框字

**Comment by 03128crz** [comment]
想问下字幕是什么字体的

**Comment by beimen** [comment]
字幕文件请从Github项目页中下载，没有字体的概念。遇到乱码时使用的文本编辑器推荐使用textmate。

**Comment by huangshisong** [comment]
已经OK了 O(∩_∩)O谢谢


 




------------------ 原始邮件 ------------------
发件人: "james";<notifications@github.com>;
发送时间: 2015年4月8日(星期三) 中午12:43
收件人: "x140yu/Developing_iOS_8_Apps_With_Swift"<Developing_iOS_8_Apps_With_Swift@noreply.github.com>; 
抄送: "黄世淞"<huangshisong@qq.com>; 
主题: Re: [Developing_iOS_8_Apps_With_Swift] 中文字幕乱码反馈用的issue (#131)




唉，使用文本编辑打开以UTF-8保存还是方框字

**Comment by sun9700** [comment]
编码已经是UTF8了，乱码是结束符引起的，另存时选择DOS terminator。Win下UltraEdit可以改。
![qq 20150416082830](https://cloud.githubusercontent.com/assets/10956421/7171978/b6f2bd20-e412-11e4-94bc-0e44d35c83dd.png)

**Comment by oMengLvRong** [comment]
用vlc播放视频为什么会断掉？

**Comment by Jerrylyn** [comment]
谢谢！

**Comment by gpl7740** [comment]
第一课字幕是方块字，其他课不知道，记事本另存为utf-8,Win下UltraEdit另存时选择DOS terminator。都没作用，VLC media player

**Comment by gpl7740** [comment]
记事本另存为utf-8,用kmplayer就可以了

**Comment by maxzsc** [comment]
win下使用射手影音
另存为unicode big endian就不是乱码了。

**Comment by GDMelon** [comment]
用在win上用VLC，另存为utf-8好像没啥用，中文还是方块的。用影音射手解决了！
