### ISSUE TITLE
「任务分配」7. Multiple MVCs

### ISSUE THREAD

**Issue by AustinChou** [x140yu/Developing_iOS_8_Apps_With_Swift#157]
春节假期已经接近尾声，第七课的翻译和校对工作准备开始了。
有兴趣的同学，请在下面留言是参与**翻译**任务还是**校对**任务，或者两者都可以参与。

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 500|AustinChou|true|true|
|501 ~ 1000|leonlianght|true|true|
|1001 ~ 1300|hotogwc|true|true
|1301 ~ 1600|yang0013|true|true
|1601 ~ 1900|whatya|true|true
|1901 ~ 2200|x140yu|true|true
|2201 ~ 2505|zobnec|true|true

## 校对人员
| 字幕序号 | 校对人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|Hs-Yeah|true|true
|301 ~ 600|guyigenius|true|true
|601 ~ 900|lincolnge|true|true
|901 ~ 1200|hbwang85|true|true
|1201 ~ 1500|X140Yu|true|true
|1501 ~ 1800|X140Yu|true|true
|1801 ~ 2100|AustinChou|true|true
|2101 ~ 2505|X140Yu|true|true

**Comment by Hs-Yeah** [comment]
领校对任务

**Comment by guyigenius** [comment]
领校对任务

**Comment by hotogwc** [comment]
假期归来，领翻译

**Comment by yang0013** [comment]
领翻译

**Comment by whatya** [comment]
领翻译

**Comment by hotogwc** [comment]
确认收到，开始翻译

**Comment by x140yu** [comment]
翻译+校对

**Comment by zobnec** [comment]
领翻译

**Comment by x140yu** [comment]
@yang0013 @whatya @zobnec 请确认翻译任务

**Comment by whatya** [comment]
确认收到

**Comment by zobnec** [comment]
确认收到

**Comment by yang0013** [comment]
确认收到

**Comment by bsklqgy** [comment]
最近怎么没动静

**Comment by lincolnge** [comment]
领校对任务

**Comment by Hs-Yeah** [comment]
确认收到校对任务

**Comment by hbwang85** [comment]
Available to work on this task

**Comment by lincolnge** [comment]
确认收到校对任务

**Comment by hbwang85** [comment]
确认收到校对任务

**Comment by x140yu** [comment]
@guyigenius 请确认任务

**Comment by guyigenius** [comment]
确认收到，马上完成。
