### ISSUE TITLE
需要预留「校对」任务的，到这里 comment

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#17]
根据人数分配任务，校对的标准参照项目内的文档。

**Comment by leon390422914** [comment]
领任务

**Comment by beimen** [comment]
几个建议：1.之前已经参与翻译的同学，尽可能对全片进行浏览，自己先保证翻译的一致性。2.如果校对人员充足，还是要按行分配下工作。3.校对是一个长期工作，如果某一天翻译到后面发现前面翻译有问题，还是要pull和merge的。

**Comment by x140yu** [comment]
@beimen 收到。我也认同你的观点，校对是个长期工作，而且一定要多次进行，随着项目的进行慢慢调整分工吧，我相信大家都这么认真，一定可以做得很好。

**Comment by supergrubby** [comment]
> 1.之前已经参与翻译的同学，尽可能对全片进行浏览，自己先保证翻译的一致性。

这个肯定会有一些问题。比如说对于对同一个名词是选择保留还是翻译，如果翻译了是否一致。
因为是刚开始，肯定会有一些出入，我们可以补充完善word list，好作为之后的参考。

但是因为每个人负责的区域不同，进行一致性的工作还是让校验的同学来做比较好，这样可以避免理解的偏差。

我们可以都参与到word list的讨论里。

**Comment by CrazyZombies** [comment]
报名！

**Comment by summerYin** [comment]
算我一个

**Comment by TongFangyuan** [comment]
我来学习下，希望认领校对任务

**Comment by lilyorlucy** [comment]
报名！

**Comment by changyu496** [comment]
报名，先认领校对任务

**Comment by zobnec** [comment]
怎么领任务？我是在cocoachina上看到这个项目的，我是做iOS开发的，参加过3dm 游戏汉化……可以参与不？

**Comment by beimen** [comment]
在这里回复，然后建议你加入这个QQ群：

CS193P 翻译组，群号码：277542197
