### ISSUE TITLE
「任务分配」8. View Controller Lifecycle, Autolayout

### ISSUE THREAD

**Issue by AustinChou** [x140yu/Developing_iOS_8_Apps_With_Swift#170]
在和X140Yu商量之后，第八课的翻译准备测试使用 [Transifex](https://www.transifex.com/organization/developing-ios-8-apps-with-swift/) 平台来进行合作，对于想参加第八课翻译的同学，请在自助申请加入的 Team 或者留言。
Transifex 平台不需要使用到 Git，所以对于 Git 不熟悉的同学也可以一起参与啦！

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|AustinChou|true|true|
|301 ~ 600|zobnec|true|true
|601 ~ 900|lincolnge|true|true
|901 ~ 1200|X140Yu|true|true
|1201 ~ 1500|hotogwc|true|true
|1501 ~ 1800|X140Yu|true|true
|1801 ~ 2145|whatya|true|true

## 校对人员

**Comment by hotogwc** [comment]
已申请加入团队

**Comment by zobnec** [comment]
确认收到

**Comment by hotogwc** [comment]
确认收到

**Comment by whatya** [comment]
确认收到

**Comment by lincolnge** [comment]
确认收到

**Comment by yuzixun** [comment]
收到

**Comment by iSmartie** [comment]
领校对任务

**Comment by zobnec** [comment]
我已经翻译完很久了…改下状态吧……
