### ISSUE TITLE
「任务分配」9. Scroll View and Multithreading

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#188]
跟上一节一样，可以使用 Git 或者 [Transifex](https://www.transifex.com/projects/p/9-scroll-view-and-multithreading/) 提交翻译，需要任务的请 comment

## 翻译人员
| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|X140Yu|true|true
|301 ~ 600|hotogwc|true|true
|601 ~ 900|hotogwc|true|true
|901 ~ 1200|yang0013|true|true
|1201 ~ 1500|DavidHu0921|true|true
|1501 ~ end|X140Yu|true|true

**Comment by DavidHu0921** [comment]
求任务

**Comment by hotogwc** [comment]
领翻译

**Comment by yang0013** [comment]
领翻译

**Comment by hotogwc** [comment]
确认收到

**Comment by DavidHu0921** [comment]
领翻译

**Comment by x140yu** [comment]
@yang0013 @DavidHu0921 请确认任务

**Comment by DavidHu0921** [comment]
收到！

**Comment by yang0013** [comment]
收到！

**Comment by hotogwc** [comment]
600-900没人的话给我吧

**Comment by x140yu** [comment]
@hotogwc 好的，任务已分配

**Comment by yang0013** [comment]
901-1200 提交了，已经合并了呀。状态没改？
