### ISSUE TITLE
3. Applying MVC 翻译任务分配

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#19]
由于这次翻译列表人比较多，所以采取每人100行的形式分发任务。

| 字幕序号 | 翻译人员 |是否完成|
|---------|---------|---|
|1 ~ 100 |ShadowPlayer|true|
|101 ~ 200|showhilllee|true|
|201 ~ 300|yang0013|true|
|301 ~ 400|hotogwc|true|
|401 ~ 500|singro||
|501 ~ 600|zenghaojim33||
|601 ~ 700|leon390422914|true|
|701 ~ 800|joeytat|true|
|801 ~ 900|bluekurk|true|
|901 ~ 1000|reinventgithub|true|
|1001 ~ 1100|DavidHu0921|true|
|1101 ~ 1200|qiaoyu314||
|1301 ~ 1400|TongFangyuan|true|
|1401 ~ 1500|lynulzy||
|1501 ~ 1600|Hazel512|true|
|1601 ~ 1700|michaelpassion|true|
|1701 ~ end|VictorTran1023||

**Comment by leon390422914** [comment]
copy that.

**Comment by TongFangyuan** [comment]
copy that

**Comment by hotogwc** [comment]
roger that

**Comment by zenghaojim33** [comment]
affirmative

**Comment by DavidHu0921** [comment]
got it

**Comment by singro** [comment]
copy.

**Comment by Duoduo789** [comment]
can i join this project?

**Comment by x140yu** [comment]
@Duoduo789 Sure. 可以先加入 QQ 群：277542197 到时有任务的时候就会通知了

**Comment by yang0013** [comment]
copy that
