### ISSUE TITLE
「任务分配」10 - 17 翻译任务分配

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#206]
iTunes U 上面的课程已经全部更新完毕了。
寻找几位同学，每人承包剩下的一集，承包期间，一个月左右完成就可以。
觉得没问题的，请 comment

|subtitle|翻译人员|确认收到|确认完成|
|---------|---------|---|---|
|10. Table View|X140Yu|true|true
|11. Unwind Segues, Alerts, Timers, View Animation|joeytat|true|true
|12. Dynamic Animation|AustinChou + X140Yu|true|true
|13. Application Lifecycle and Core Motion|yang0013|true|true
|14. Core Location and MapKit|hotogwc|true|true
|15. Modal Segues|changyu496|true|true
|16. Camera, Persistence, and Embed Segues|SOOBE + bluekurkI|true|true
|17. Internationalization and Settings|lincolnge|true|true

**Comment by joeytat** [comment]
对 11 很感兴趣，领一集~~~

**Comment by yang0013** [comment]
翻译 13

**Comment by lincolnge** [comment]
求17集...

**Comment by hotogwc** [comment]
求一集，哪集都行

**Comment by hotogwc** [comment]
收到，第14集

**Comment by lincolnge** [comment]
收到.

**Comment by x140yu** [comment]
@joeytat @yang0013 任务已分配

**Comment by joeytat** [comment]
收到

**Comment by yang0013** [comment]
收到

**Comment by kylinroc** [comment]
领16

**Comment by SOOBEI** [comment]
领16

**Comment by rickierYun** [comment]
快一个月了我想知道各位翻译的同学进展怎么样了，前面的课程已经学完了，谢谢

**Comment by x140yu** [comment]
@rickierYun 再等等吧，大家可能都比较忙。我那集五一假期尽量搞定

**Comment by rickierYun** [comment]
谢谢，辛苦了！

**Comment by hotogwc** [comment]
答应了说这周交，但是我病了。。。保证下周提交，不好意思

**Comment by x140yu** [comment]
没事儿，好好养病，身体比较重要

发自我的 iPhone

**Comment by lixin147741** [comment]
@x140yu 同学，已经翻译好的但是没校对的可以先放出来吗，更新到百度网盘就可以~~谢谢啦~

**Comment by Heisenbean** [comment]
10-17有翻译完的吗?翻译完,先传网盘?

**Comment by rickierYun** [comment]
13的时间轴有问题，第三句话，应该是在9秒左右

**Comment by aiqiuqiu** [comment]
为什么最近更新这么慢

**Comment by riversideview** [comment]
阿西吧，怎么后面的翻译完了，前面的还没翻译。

**Comment by cache0928** [comment]
12什么时候可以翻译完呢？

**Comment by AustinChou** [comment]
@cache0928 抱歉，最近比较忙，Lecture 12 已经开始翻译了，可能还需要几天的时间。

**Comment by fightingForYou** [comment]
@AustinChou 大概还要多久才能翻译完啊。。
