### ISSUE TITLE
「任务分配」1. Logistics, iOS 8 Overview

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#51]
| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300 |ann2bad|true|true|
|301 ~ 600|jieyuanz|true|true|
|601 ~ 900|hhgz9527|true|true|
|901 ~ 1200|wdanxna|true|true|
|1201 ~ 1349|beimen|true|true|

| 字幕序号 | 校对人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|x140yu,beimen|	true|true|
|301 ~ 600|beimen,changyu496|true|true|
|601 ~ 800|x140yu|true|true|
|801 ~ 1100|beimen|true|true
|1101 ~ 1348|leonlianght|true|true

**Comment by wpf123** [comment]
thank you
