### ISSUE TITLE
「任务分配」3. Applying MVC

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#55]
### 翻译人员

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 100 |ShadowPlayer|true|true|
|101 ~ 200|showhilllee|true|true|
|201 ~ 300|yang0013|true|true|
|301 ~ 400|hotogwc|true|true|
|401 ~ 500|singro|true|true|
|501 ~ 600|zenghaojim33|true|true
|601 ~ 700|leonlianght|true|true|
|701 ~ 800|joeytat|true|true|
|801 ~ 900|bluekurk|true|true|
|901 ~ 1000|reinventgithub|true|true|
|1001 ~ 1100|DavidHu0921|true|true|
|1101 ~ 1200|DavidHu0921|true|true
|1201 ~ 1300|x140yu|true|true|
|1301 ~ 1400|TongFangyuan|true|true|
|1401 ~ 1500|Duoduo789|true|true
|1501 ~ 1600|Hazel512|true|true|
|1601 ~ 1700|michaelpassion|true|true|
|1701 ~ end|x140yu|true|true|

### 校对人员

| 字幕序号 | 校对人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|leonlianght|true|true
|301 ~ 600|TongFangyuan|true|true
|601 ~ 900|AustinChou|true|true
|901 ~ 1200|X140Yu|true|true
|1201 ~ 1500|iSmartie|true|true
|1500 ~ end|urmyfaith|true|true

**Comment by leon390422914** [comment]
领校对
怎么没有人领校对任务？我打开的方式不对么？。。。

**Comment by iSmartie** [comment]
12分41秒把enum写成email了，翻译没有改过来，校对注意~
