### ISSUE TITLE
关于 issue 区的几点说明

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#57]
## 怎么领任务？

1. 每节新内容发布以后，我都会在这里开一个当节的 「任务分配」issue
2. 想要领任务的同学，自愿到那里 comment 领取任务，请注明是「翻译」还是「校对」
3. 我会根据当节领任务的人数下发任务，为避免冲突，任务最低量为100条
4. 之前排队但没有接到任务的同学，你们仍在队列中，请做好接任务的准备（排完队列即失效）

## 如果有了任务我该做什么？

0. 请把自己的群昵称改为 GitHub 用户名
1. 与我 QQ 联系确认，我会更新「确认收到」状态为 `true`
2. 接收到任务24小时之内不联系我的，视为放弃任务
3. 翻译和校对的过程中有拿不准的地方，进入当节的讨论 issue 讨论（如这个词该不该翻译，该翻译成什么，此 issue 长期有效）

## 任务的期限

1. 每100条字幕有24小时的时间提交
2. 如果忙碌一定要及时提出来，方便我们把任务转给其他人

### 翻译、校对任务的序号**不是**指字幕文件中行数，而是指
```
67 <----此处的数字
 00:03:04,860 --> 00:03:06,960
 we talked about the NSNumber format and all that.
```

本项目 QQ 群：277542197

**Comment by lastcc** [comment]
"...you've never seen AnyObject in action"
http://open.163.com/movie/2015/2/M/U/MAIKHN60A_MAIP1D3MU.html
约11分的时候 翻错了 ［你永远不会在action中看到AnyObejct］应该是 目前为止，你还没实际体会AnyObject。看到这句都错了真觉得：诶。

还有前面有一句什么翻译成了什么为了效率…… 应该是保存偏好

**Comment by Hs-Yeah** [comment]
@lastcc 可能网易公开课在校对完成之前就已经把视频压好上传了吧，发现字幕有翻译错误欢迎提交 PR

**Comment by Hs-Yeah** [comment]
@lastcc 刚翻看了提交历史，这一段是我校对的，记得当初这一句不知道改不改，最后留在那里了。稍后我再修正
