### ISSUE TITLE
「任务分配」4. More Swift and Foundation Frameworks

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#61]
### 翻译人员：

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 100 |Joeytat|true|true
|101 ~ 200|MrCocoa|true|true
|201 ~ 300|CrazyZombies|true|true
|301 ~ 400|whatya|true|true
|401 ~ 500|zobnec|true|true
|501 ~ 600|AustinChou|true|true
|601 ~ 700|hotogwc|true|true
|701 ~ 800|Devtll|true|true
|801 ~ 900|yang0013|true|true
|901 ~ 1000|TongFangyuan|true|true
|1001 ~ 1100|AustinChou|true|true
|1101 ~ 1200|DavidHu0921|true|true
|1201 ~ 1300|yang0013|true|true
|1301 ~ 1400|hotogwc|true|true
|1401 ~ 1500|AustinChou|true|true
|1501 ~ 1600|AustinChou|true|true
|1601 ~ end|AustinChou|true|true

## 校对人员

| 字幕序号 | 校对人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|x140yu|true|true
|301 ~ 600|clairehu|true|true
|601 ~ 900|x140yu|true|true
|901 ~ 1200|iSmartie|true|true
|1201 ~ 1500|x140yu|true|true
|1500 ~ end|AustinChou|true|true

注明你需要的任务，是「翻译」还是「校对」或者「Both」

**Comment by DavidHu0921** [comment]
随时可以翻译，求任务

**Comment by zobnec** [comment]
收到，想以翻译为主O(∩_∩)O~

**Comment by hotogwc** [comment]
翻译，谢谢

**Comment by Duoduo789** [comment]
求任务，翻译

**Comment by AustinChou** [comment]
Both

**Comment by DavidHu0921** [comment]
确认收到，正在翻

**Comment by yang0013** [comment]
收到～

**Comment by TongFangyuan** [comment]
收到

**Comment by joeytat** [comment]
现在还可以认领 1~100 及 301~400 翻译吗？

**Comment by clairehu** [comment]
校对 谢谢~

**Comment by changyu496** [comment]
可以参加校对，谢谢!

**Comment by whatya** [comment]
求翻译，时间充裕！

**Comment by hotogwc** [comment]
我200行都翻译完了，继续领也没问题，最近时间比较多

**Comment by whatya** [comment]
确认收到

**Comment by andyRon** [comment]
求任务，翻译，校对都可以

**Comment by leon390422914** [comment]
领1201 ~ 1300，如果还缺的话

**Comment by iSmartie** [comment]
校对，求任务

**Comment by leon390422914** [comment]
校对

**Comment by Hs-Yeah** [comment]
领校对

**Comment by michaelpassion** [comment]
认领翻译

**Comment by clairehu** [comment]
确认收到校对任务

**Comment by aixion** [comment]
收到，群主，是这个Aixion, 不是那个Aixon,谢谢，领校对任务，翻译也行

**Comment by Aixon** [comment]
谢谢，白天要上班，晚上搞起…

**Comment by li-xinyang** [comment]
可参加翻译，不想用QQ。

**Comment by beimen** [comment]
此刻翻译校对已满，建议去其他分配任务中的课程排队。
