### ISSUE TITLE
翻译、校对讨论帖

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#65]

**Comment by leon390422914** [comment]
operand和operation怎么翻译比较恰当？需要统一一下吗？校对的时候发现两个人的翻译是不一样的。

**Comment by whatya** [comment]
操作&操作符 or 运算&运算符？

**Comment by leon390422914** [comment]
操作数&运算符 呢？，其实就是一个是数字一个是加减乘除符号。。怎样表达会通俗易懂一点？

**Comment by CrazyZombies** [comment]
“ bag of bits” 怎么翻译比较好？

在第四课中讲解 NSData 时出现的，意思是将 NSData 中的数据解释为 “一堆的比特数据” ，怎么翻译比较好呢？其他集中有出现吗？

**Comment by beimen** [comment]
我觉得比特包应该可以用的。

**Comment by Hs-Yeah** [comment]
建议创建一个专用名词的列表，在 readme 里面链接一下，这边讨论完的可以在那边添加上去，方便翻译、校对时的工作

**Comment by Hs-Yeah** [comment]
有个问题，字幕文件行末的换行符是用 Unix 样式的 LF，还是用 Windows 样式的 CRLF 呢？

**Comment by beimen** [comment]
应该是个LF，至于专用的名词列表，这里边有几位同学都在视图建立一个对照表，但是好像不是很好建的样子。
