### ISSUE TITLE
「任务分配」5. Objective-C Compatibility, Property List, Views

### ISSUE THREAD

**Issue by x140yu** [x140yu/Developing_iOS_8_Apps_With_Swift#91]
为了大家翻译的时候能专注，已经把原来字幕有错误的地方都修正了（也有可能有我没发现的）。
希望大家翻译的时候能认真，把视频看过一遍再翻译，不要硬对着字幕翻译。
质量是第一的，速度可以慢。

好了，可以领任务的留言吧~

| 字幕序号 | 翻译人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 200|hotogwc|true|true
|201 ~ 400|yang0013|true|true
|401 ~ 600|AustinChou|true|true
|601 ~ 800|whatya|true|true|true
|801 ~ 1000|zobnec|true|true
|1001 ~ 1200|bluekurk|true|true
|1201 ~ 1600|leonlianght|true|true
|1601 ~ 1853|X140Yu|true|true

## 校对人员

| 字幕序号 | 校对人员 |确认收到|确认完成|
|---------|---------|---|---|
|1 ~ 300|leonlianght|true|true
|301 ~ 600|Hs-Yeah|true|true
|601 ~ 900|changyu496|true|true
|901 ~ 1200|guyigenius|true|true
|1201 ~ 1500|iSmartie|true|true
|1501 ~ 1853|AustinChou|true|true

**Comment by hotogwc** [comment]
翻译，前两课都是看视频翻译的，200行干了小半天

**Comment by yang0013** [comment]
领任务～

**Comment by AustinChou** [comment]
翻译，校对都可。

**Comment by Hs-Yeah** [comment]
领校对~

**Comment by whatya** [comment]
确认收到

**Comment by zobnec** [comment]
领翻译~

**Comment by x140yu** [comment]
@hotogwc 在群里把昵称改一下，PS，任务已发放给你，请确认

**Comment by hotogwc** [comment]
改好啦，确认收到

**Comment by bluekurk** [comment]
领翻译任务

**Comment by changyu496** [comment]
好久没冒泡，继续领校对任务

**Comment by guyigenius** [comment]
领校对任务

**Comment by Aixon** [comment]
领校对任务

**Comment by yang0013** [comment]
领校对任务

**Comment by michaelpassion** [comment]
领翻译任务

**Comment by AustinChou** [comment]
翻译或校对

**Comment by jcdfnz** [comment]
开启垃圾邮件拦截，刚看到
翻译





在 2015-02-14 21:55:43，"Yifei Zhou" <notifications@github.com> 写道：


翻译或校对

**Comment by Hs-Yeah** [comment]
第五课 301- 600 校对确认收到
