### ISSUE TITLE
你好，可不可以把文档也翻译了呢？

### ISSUE THREAD

**Issue by ZsIsMe** [x140yu/Developing_iOS_8_Apps_With_Swift#93]
我觉得每一章节的PDF对学习都是有极大帮助的，且文字量也不是很多，为什么不顺便把他也翻译了呢？
相信很多人（比如我）会出力的。。。
你认为呢？

**Comment by beimen** [comment]
早期有翻译的，但是国内连接GitHub速度较慢，这类Slide翻译完体积比较大（一个Slide约4M，整个项目除掉Slide后不到1M），所以后来不翻译了。如果只纯翻译文本有点问题，所以现在没弄了。

**Comment by AustinChou** [comment]
@ZsIsMe 
我的建议是，与其等待别人翻译，不如自己学好英语。
想入门（精通也一样）iOS开发，必须阅读大量英文资料和书籍，翻译的都是二手资料，肯定不如一手的准确。
@beimen 解释比较清楚了。
